# Generated by Django 2.0 on 2017-12-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glassware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glassware_name', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=25)),
                ('grade', models.CharField(max_length=2)),
                ('data_enter', models.DateField(auto_now=True)),
                ('manufacutrer', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='chemicals',
            old_name='manufacuturer',
            new_name='manufacturer',
        ),
    ]
