# Generated by Django 2.0 on 2017-12-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20171226_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glassware',
            old_name='manufacutrer',
            new_name='manufacturer',
        ),
        migrations.AddField(
            model_name='glassware',
            name='quantity',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
